# Generated by Django 3.2 on 2024-02-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fully_paid',
            field=models.CharField(blank=True, choices=[('ДА', 'ДА'), ('НЕТ', 'НЕТ')], max_length=3, null=True, verbose_name='Полностью оплатил'),
        ),
    ]
