# Generated by Django 3.2 on 2024-02-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20240219_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='vacation_end_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vacation_start_date',
        ),
    ]
