# Generated by Django 4.2 on 2024-03-28 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'Приглашение', 'verbose_name_plural': 'Приглашения'},
        ),
    ]
