# Generated by Django 3.2 on 2024-02-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240219_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='has_experience',
            field=models.BooleanField(default=False, verbose_name='Опыт работы'),
        ),
    ]
